on: [push]

jobs:
        build_main:
                runs-on: ubuntu-latest
                steps:
                        - run: mvn compile

        test_main:
                runs-on: ubuntu-latest
                needs: [build_main]
                steps:
                        - run: mvn test
